### ISSUE TITLE
Feature request: async support

### ISSUE THREAD

**Issue by baudouinth** [ecmwf/cdsapi#38]
A simple use of `aiohttp` for requesting and `aiofiles` for writing to disk would greatly improve the usability of `cdsapi` when launching several parallel requests.

**Comment by EddyCMWF** [comment]
Hi,
the cdsapi does not offer any support for parallel submitting requests. This is intentional as to make best use of our queueing system it is advised to submit serially. The systems we have in place are to ensure fair usage for all our users.
Many thanks,
Eddy

**Comment by bgiebl** [comment]
For anyone landing here looking for a practical solution: I built https://github.com/bgiebl/cdsswarm, a CLI tool  
  that submits multiple CDS requests with configurable concurrency.                                                 
                                                                                                                    
  I understand the fair-usage concern @EddyCMWF raised — cdsswarm doesn't try to circumvent the queue. Each request 
  still waits its turn on the server. The main benefit is overlapping that server-side queue/processing time across 
  requests, so you're not waiting sequentially for each one to complete before submitting the next. In a benchmark  
  with 4 monthly ERA5 files, 4 workers finished in 7m39s vs 24m02s sequentially (3.1x speedup), with most of the    
  gain coming from overlapped waiting rather than download parallelism.

  It also provides an interactive TUI to monitor progress, automatic retries, session resume, and a generate
  subcommand for templating request files.
