### ISSUE TITLE
Best practices when sending multiple requests

### ISSUE THREAD

**Issue by AlFontal** [ecmwf/cdsapi#42]
As it stands now, I usually make several requests to split in chunks the datasets I fetch through the API for less memory-intensive processing. 

However, there is no way to send a list of requests (I am just using for loops to do so now) and my requests usually take ~20 min in queue and 1-2 min downloading, which makes fetching the datasets a quite time-consuming process.

Is there any way to speed this up?

**Comment by EddyCMWF** [comment]
Hi @AlFontal ,
This is the recommended way to use the cdsapi. A believe that since upgrading various pieces of software and infrastructure in the CDS our queues are significantly reduced since you originally posted your issue. 

Also, I recommend the C3S user support channel for quicker responses to queries regarding requests and best practices:
https://cds.climate.copernicus.eu/cdsapp#!/usersupport

All the best,
Eddy
