### ISSUE TITLE
 Max retries exceeded with url, timed out.

### ISSUE THREAD

**Issue by mmichelli** [ecmwf/cdsapi#56]
I started getting this error:

`Recovering from connection error [HTTPSConnectionPool(host='cds.climate.copernicus.eu', port=443): Max retries exceeded with url: /api/v2/tasks/46f7822a-449a-499f-bbcf-c3cdc2b77420 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8b9faf7400>, 'Connection to cds.climate.copernicus.eu timed out. (connect timeout=None)'))], attemps 0 of 500
Retrying in 120 seconds
`

I've tried adding a timeout.

**Comment by pierreloicq** [comment]
same same

**Comment by evelynlee999** [comment]
I wonder if you solved the error?

**Comment by pierreloicq** [comment]
no but you can download the file despite this

**Comment by EddyCMWF** [comment]
Hi,
This generally means that the connection the Client connection to the CDS was dropped whilst the data request was running. As we cache the results, resubmitting the same request should return the result from your previous request*.

*unless the first request is still running on the CDS, otherwise you will get a "queued" status whilst the first request completes, at which point you will get the result from the first request.

Thanks,
Eddy
